Warning: OMP_NUM_THREADS=16 is greater than available PU's
Warning: OMP_NUM_THREADS=16 is greater than available PU's
Traceback (most recent call last):
  File "pytorch_experiment.py", line 386, in <module>
    main_experiment()
  File "pytorch_experiment.py", line 100, in main_experiment
    store=True)
  File "/gpfs/alpine/gen011/world-shared/native-build/anaconda3/envs/WML161/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 442, in init_process_group
    timeout=timeout)
  File "/gpfs/alpine/gen011/world-shared/native-build/anaconda3/envs/WML161/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 511, in _new_process_group_helper
    prefix_store = PrefixStore(group_name, store)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. torch.distributed.PrefixStore(arg0: str, arg1: torch.distributed.Store)

Invoked with: '0', True

------------------------------------------------------------
Sender: LSF System <lsfadmin@batch2>
Subject: Job 537677: <data_challenge_modeling> in cluster <summit> Done

Job <data_challenge_modeling> was submitted from host <login1> by user <shutoaraki> in cluster <summit> at Fri Aug  2 10:56:23 2019
Job was executed on host(s) <1*batch2>, in queue <batch>, as user <shutoaraki> in cluster <summit> at Fri Aug  2 10:56:30 2019
                            <42*h36n08>
</ccs/home/shutoaraki> was used as the home directory.
</ccs/home/shutoaraki/datachallenge2/pytorch> was used as the working directory.
Started at Fri Aug  2 10:56:30 2019
Terminated at Fri Aug  2 11:01:22 2019
Results reported at Fri Aug  2 11:01:22 2019

The output (if any) is above this job summary.

